---
title: "Studying Vaccine Effectiveness through Test-Negative Designs"
author: "Ray Pomponio"
date: "2024-03-19"
categories: [analysis, biomedical]
draft: true
---

### Introduction

Recently, epidemiological studies have focused on monitoring vaccine effectiveness (VE) through a variety of study designs. One such study design common for monitoring VE in influenza is the test-negative design (TND). In this post I summarize key characteristics of the TND and comment on its known limitations in estimating VE.

## History of Test-Negative Designs

Test-negative designs appear to be a recent development within epidemiology and public health. In the context of influenza vaccine surveillance, the earliest scientific publications with TNDs are from studies conducted in the mid-2000s.[^1]

Despite the relative youth of this study design, TNDs are now common and impactful ways of monitoring vaccines. The United States' Centers for Disease Control (CDC) recently evaluated the effectiveness of the 2023-24 influenza vaccine using a TND.[^2] Similarly, the CDC estimated the VE of Nirsevimab against RSV infection in infants,[^3] finding that the monoclonal antibody was 90% effective against RSV-related hospitalizaions based on the results of a TND study.

The current examples of TNDs illustrate the study design's potential. It is likely that TNDs have become so common because they are cost-effective (versus cohort studies and randomized control trials), they are thought to reduce certain types of biases, and they are relatively easy to implement in monitoring public health outcomes, such as hospitalizations.

[^1]: Fukushima, W., & Hirota, Y. (2017). Basic principles of test-negative design in evaluating influenza vaccine effectiveness. Vaccine, 35(36), 4796–4800. https://doi.org/10.1016/j.vaccine.2017.07.003
[^2]: Frutos, A. M., Price, A. M., Harker, E., Reeves, E. L., Ahmad, H. M., Murugan, V., Martin, E. T., House, S., Saade, E. A., Zimmerman, R. K., Gaglani, M., Wernli, K. J., Walter, E. B., Michaels, M. G., Staat, M. A., Weinberg, G. A., Selvarangan, R., Boom, J. A., Klein, E. J., Halasa, N. B., … CDC Influenza Vaccine Effectiveness Collaborators (2024). Interim Estimates of 2023-24 Seasonal Influenza Vaccine Effectiveness - United States. MMWR. Morbidity and mortality weekly report, 73(8), 168–174. https://doi.org/10.15585/mmwr.mm7308a3
[^3]: Moline, H. L., Tannis, A., Toepfer, A. P., Williams, J. V., Boom, J. A., Englund, J. A., Halasa, N. B., Staat, M. A., Weinberg, G. A., Selvarangan, R., Michaels, M. G., Sahni, L. C., Klein, E. J., Stewart, L. S., Schlaudecker, E. P., Szilagyi, P. G., Schuster, J. E., Goldstein, L., Musa, S., Piedra, P. A., … Dawood, F. S. (2024). Early Estimate of Nirsevimab Effectiveness for Prevention of Respiratory Syncytial Virus-Associated Hospitalization Among Infants Entering Their First Respiratory Syncytial Virus Season - New Vaccine Surveillance Network, October 2023-February 2024. MMWR. Morbidity and mortality weekly report, 73(9), 209–214. https://doi.org/10.15585/mmwr.mm7309a4

## Key Characteristics of Test-Negative Designs

There are several common characteristics of the test-negative design. To explain these characteristics, I will use an example with influenza as the context. Influenza ("flu") is a seasonal virus that can cause acute respiratory infections (ARIs). To reduce the public health burden of influenza, a seasonal flu vaccine is commonly circulated in the United States and other countries around the world. Suppose it's a new flu season and our aim is to study the effectiveness of the latest vaccine against hospitalizations. This is the classic case to highlight the utility of the test-negative design.

We conduct a TND by recruiting in our study patients who develop ARI symptoms and are hospitalized at a specific clinic due to their symptoms; this is our recruitment population. Next, all those who enroll in the study are tested for flu, typically with rapid diagnostic testing. Finally, the enrollees who test positive for influenza are considered "cases", while the remaining enrollees are considered "controls". For every enrollee, we would identify their flu vaccination status based on a government registry or the electronic health record. Our primary endpoint is the vaccine effectiveness (VE) against hospitalizations, which can be estimated as:

$$
\hat{VE}_{hospoitalizaion}=1-\hat{OR}_{Vax,Case:Ctrl}
$$

where $\hat{OR}_{Vax,Case:Ctrl}$ is the ratio of the odds of vaccination in cases versus the odds of vaccination in controls. It is worth noting that this is an unadjusted odds ratio, but an adjusted ratio might easily be computed using logistic regression; this would permit adjusting for potential confounding variables, such as age and sex.

It is important to distinguish between the characteristics of the TND and those of the randomized controlled trial (RCT), which is generally considered the "gold standard" of epidemiological evidence. In an RCT, participants are recruited before they get vaccinated and before they've been exposed to the season's flu virus. The key characteristic of an RCT is that participants will be *randomized* to receiving either the vaccine or a placebo. Throughout an RCT study, researchers will follow-up with participants to monitor any outcomes of interest, such as infections and hospitalizations. In contrast, participants in a TND are recruited after symptoms develop and they show up at a hospital clinic. Thus the recruitment populations are fundamentally different between RCTs and TNDs.

## Limitations of Test-Negative Designs

Test-negative designs are praised for their improved accuracy in estimating vaccine effectiveness (VE). One of the foundational papers for the basis of TNDs argued that the design is less susceptible to bias resulting from differences in health care-seeking behavior between vaccinated and unvaccinated populations.[^4] The reason is that the TND only analyzes individuals who have already sought care, by definition. Thus any differential likelihood in health care-seeking behavior is unlikely to impact the estimates of VE from a TND study.

However, more recent work has elucidated a number of potential limitations of TNDs and their susceptibility to biases. For example, vaccination receipt might be associated with healthy behaviors such as hand washing. If those individuals who receive the vaccine also engage in healthier behaviors than their unvaccinated counterparts, then the results of a TND that does not adjust for hand washing will be confounded.

[^4]: Jackson, M. L., & Nelson, J. C. (2013). The test-negative design for estimating influenza vaccine effectiveness. Vaccine, 31(17), 2165–2168. https://doi.org/10.1016/j.vaccine.2013.02.053





