project:
  type: website
  output-dir: docs

website:
  title: "rpomponio.github.io"
  navbar:
    right:
      - about.qmd
      - adventure.qmd
      - icon: github
        href: https://github.com/rpomponio
      - icon: linkedin
        href: https://scholar.google.com/citations?user=TxEcZMMAAAAJ&hl=en
format:
  html:
    theme: sandstone
    css: styles.css



