project:
  type: website
  output-dir: docs

website:
  title: "rpomponio.github.io"
  navbar:
    right:
      - about.qmd
      - adventure.qmd
      - icon: github
        href: https://github.com/rpomponio
      - icon: linkedin
        href: www.linkedin.com/in/ray-pomponio-7229302a5
format:
  html:
    theme: sandstone
    css: styles.css



