project:
  type: website
  output-dir: docs
  resources: 
    - "photos/*"
    - "portfolio/*"

website:
  title: "pompon.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rpomponio
      - icon: linkedin
        href: https://www.linkedin.com/in/ray-pomponio
      - icon: google
        href: https://scholar.google.com/citations?user=TxEcZMMAAAAJ&hl=en
format:
  html:
    theme: sandstone
    css: styles.css



