project:
  type: website
  output-dir: docs
  resources: 
    - "photos/*"
    - "portfolio/*"

website:
  title: "pompon.io"
  navbar:
    right:
      - text: resume
        href: portfolio/RAY-POMPONIO_cv.pdf
      - text: work sample 1
        href: portfolio/RAY-POMPONIO_power_analysis.pdf
      - text: work sample 2
        href: portfolio/RAY-POMPONIO_report-sample.pdf
      - adventure.qmd
      - about.qmd
      - icon: github
        href: https://github.com/rpomponio
      - icon: linkedin
        href: https://www.linkedin.com/in/ray-pomponio
format:
  html:
    theme: sandstone
    css: styles.css



