project:
  type: website
  output-dir: docs
  resources: 
    - "wv-24-gallery/pages/*"
    - "wv-24-gallery/images/*"
    - "RAY-POMPONIO_cv.pdf"

website:
  title: "rpomponio.github.io"
  navbar:
    right:
      - text: resume
        href: RAY-POMPONIO_cv.pdf
      - about.qmd
      - adventure.qmd
      - icon: github
        href: https://github.com/rpomponio
      - icon: linkedin
        href: https://www.linkedin.com/in/ray-pomponio
format:
  html:
    theme: sandstone
    css: styles.css



