project:
  type: website
  output-dir: docs
  resources: 
    - "wv-24-gallery/pages/*"
    - "wv-24-gallery/images/*"
    - "wv-24-gallery.html"
    - "mex-25-gallery/pages/*"
    - "mex-25-gallery/images/*"
    - "mex-25-gallery.html"
    - "portfolio/*"

website:
  title: "pompon.io"
  navbar:
    collapse: true
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Photography
        menu:
          - text: West Virginia
            href: wv-24-gallery.html
          - text: Mexico
            href: mex-25-gallery.html
      - text: GitHub
        href: https://github.com/rpomponio
        icon: github
      - text: LinkedIn
        href: https://www.linkedin.com/in/ray-pomponio
        icon: linkedin
      - text: CV
        href: "portfolio/Pomponio_Ray_CV.pdf"
        icon: file-earmark-text
      # - text: Work Samples
      #   menu:
      #     - text: Power Analysis
      #       href: portfolio/RAY-POMPONIO_power_analysis.pdf
      #     - text: Marketing Insights
      #       href: portfolio/RAY-POMPONIO_report-sample.pdf
format:
  html:
    theme: litera
    css: styles.css