project:
  type: website
  output-dir: docs

website:
  title: "rpomponio.github.io"
  navbar:
    right:
      - text: resume
        href: https://drive.google.com/file/d/1XoGeGJnlmwvz46lImtNQmXJ4vMeSfkgl/view?usp=sharing
      - about.qmd
      - adventure.qmd
      - icon: github
        href: https://github.com/rpomponio
      - icon: linkedin
        href: https://www.linkedin.com/in/ray-pomponio
format:
  html:
    theme: sandstone
    css: styles.css



