 ---
title: "Unpublished Draft"
---

## Impact of Competition Load on Winning in Men's Tennis

### Background

The cumulative time played throughout a tennis tournament has been described as 'competition load'.[^1] The effect of competition load on winning has been studied using a relatively simple model with data from Men's quarterfinals, semifinals, and finals matches.[^2] With the identification a deleterious effect of higher load on the odds of winning, there remain many unanswered questions about the nuances of this result. Does competition load equate with fatigue, for example? Also, does competition load affect all players equally, or at least players of a similar age? One can imagine many potentially interesting findings from investigating answers to these questions alone.

### Motivating Example

In the 2022 US Open, [Nick Kyrgios](https://tennisabstract.com/cgi-bin/player.cgi?p=NickKyrgios&f=A2022qqDUS_Openqq) (Aus.) entered the quarterfinals as a favorite over [Karen Khachanov](https://www.tennisabstract.com/cgi-bin/player-classic.cgi?p=KarenKhachanov&f=A2022qqDUS_Openqq) (Russia). Kyrgios was ranked 25th at the time, while Khachanov was ranked 31st. Importantly, the two opponents had experienced differnt amounts of competition load up to that point in the tournament, with the higher-ranked Kyrgios having played 9.7 hours of matches through the first four rounds, compared with Khachanov's 11 hours. Note, the typical load at this stage of a Men's Grand Slam is about 9 hours and 23 minutes of on-court time.

Did bettors miss an opportunity to capitalize on Khachanov's odds of 4.35 going into the match, which he ultimately won, upsetting Kyrgios? A model trained to predict win probability suggests this match was closer-to-even than the odds suggested. In this model, I accounted for opponent ranks and opponent competition load, as well as court surface and tournament stakes. Based on the circumstances of the [Kyrgios-Khachanov quarterfinal](https://www.tennisabstract.com/charting/20220906-M-US_Open-QF-Karen_Khachanov-Nick_Kyrgios.html), the model predicts that Kyrgios had a **54.7%** chance of winning, meaning the underdog Khachanov's odds should have been closer to 2.21. A casual tennis fan, eyeing the rankings and time played in recent matches, might not have suspected that Khachanov could overcome his higher-than-average competition load of 11 hours to win the quarterfinal. Ultimately, Khachanov was defeated in the subsequent semifinal against 7th-ranked Casper Ruud (Norway).

### Next Steps

This example from the 2022 US Open is illustrative of a possibly larger trend within professional tennis. That is, competition load can often favor the underdog in unexpected ways. It's somewhat counterintuitive that a higher competition load contributes to higher odds for the lower-ranked player, while the same is not true for higher-ranked players. Specifically, each additional hour played by the lower-ranked player is associated with 3.6% higher odds of their winning the upcoming match, controlling for opponent load and strength (95 percent conf. interval: 2.2 — 5.0%).

The model remains to be validated in a true sportsbetting experiment, but current results are suggestive of several key insights. One, competition load may not be the same as fatigue, since lower-ranked players tend to perform better when entering matches with higher load. Secondly, the odds of an upcoming match may not optimally account for competition load, as we saw in the above example. Importantly, this analysis did not account for common player age effects nor player-specific responses to load. Those components will be part of future work.

[^1]: S. Kovalchik, "Did Competition Load Help Make Medvedev a Grand Slam Champion?," Stats on the T, 31 January 2022 [Online]. http://on-the-t.com/2021/09/12/Did-Competition-Load-Help-Medvedev/.
[^2]:  S. Kovalchik, "Does greater competition load going into the second week of a Grand Slam hurt a player's win chances?," Stats on the T, 15 February 2020 [Online]. http://on-the-t.com/2020/02/15/competition-load/.


---